FROM almalinux:9
RUN dnf install nginx -y 

# FROM run:1.0
# we refered in this way also, bcoz we alredy created the image using RUN instruction

#CMD ["executable","param1","param2"]

CMD ["nginx", "-g", "daemon off;"]